const sanitizeFileName = (fileName) => {
  const cleanedFileName = fileName
    .replace(/[<>:"/\\|?*]/g, "")
    .trim()
    .replace(/\s+/g, "-");

  return cleanedFileName.toLowerCase().endsWith(".md")
    ? cleanedFileName
    : `${cleanedFileName}.md`;
};

export const exportContentAsMarkdown = (
  title,
  content,
  fileName = "tanio-ai-content.md"
) => {
  if (!content || !content.trim()) {
    throw new Error("There is no content available to export.");
  }

  const markdownContent = `# ${title || "Tanio AI Generated Content"}

${content.trim()}

---

Generated by Tanio AI
`;

  const blob = new Blob([markdownContent], {
    type: "text/markdown;charset=utf-8",
  });

  const downloadUrl = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = downloadUrl;
  link.download = sanitizeFileName(fileName);

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(downloadUrl);
};