import {
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
} from "docx";

const sanitizeFileName = (fileName) => {
  const cleanedName =
    String(fileName || "tanio-ai-content")
      .replace(/[<>:"/\\|?*]/g, "")
      .trim()
      .replace(/\s+/g, "-") || "tanio-ai-content";

  return cleanedName.toLowerCase().endsWith(".docx")
    ? cleanedName
    : `${cleanedName}.docx`;
};

const createParagraphs = (content) => {
  const paragraphs = [];
  let insideCodeBlock = false;

  const headingLevels = [
    HeadingLevel.HEADING_1,
    HeadingLevel.HEADING_2,
    HeadingLevel.HEADING_3,
    HeadingLevel.HEADING_4,
    HeadingLevel.HEADING_5,
    HeadingLevel.HEADING_6,
  ];

  for (const line of content.replace(/\r\n?/g, "\n").split("\n")) {
    if (/^\s*(`{3,}|~{3,})/.test(line)) {
      insideCodeBlock = !insideCodeBlock;
      continue;
    }

    if (insideCodeBlock) {
      paragraphs.push(
        new Paragraph({
          children: [
            new TextRun({
              text: line,
              font: "Consolas",
              size: 20,
            }),
          ],
          spacing: { after: 80 },
        })
      );
      continue;
    }

    const heading = line.match(/^(#{1,6})\s+(.+)$/);

    if (heading) {
      paragraphs.push(
        new Paragraph({
          text: heading[2],
          heading: headingLevels[heading[1].length - 1],
          spacing: { before: 200, after: 120 },
        })
      );
      continue;
    }

    if (/^\s*(?:-{3,}|\*{3,}|_{3,})\s*$/.test(line)) {
      paragraphs.push(new Paragraph({ text: "" }));
      continue;
    }

    const bullet = line.match(/^\s*[-*+]\s+(.+)$/);

    if (bullet) {
      paragraphs.push(
        new Paragraph({
          text: bullet[1],
          bullet: { level: 0 },
          spacing: { after: 100 },
        })
      );
      continue;
    }

    paragraphs.push(
      new Paragraph({
        text: line,
        spacing: { after: 120 },
      })
    );
  }

  return paragraphs;
};

export const exportContentAsDocx = async (
  title,
  content,
  fileName = "tanio-ai-content.docx"
) => {
  if (typeof content !== "string" || !content.trim()) {
    throw new Error("There is no content available to export.");
  }

  const document = new Document({
    creator: "Tanio AI",
    title: title || "Tanio AI Generated Content",
    description: "Study material exported from Tanio AI",
    sections: [
      {
        children: [
          new Paragraph({
            text: title || "Tanio AI Generated Content",
            heading: HeadingLevel.TITLE,
            spacing: { after: 240 },
          }),
          ...createParagraphs(content),
          new Paragraph({
            children: [
              new TextRun({
                text: "Generated by Tanio AI",
                italics: true,
                color: "64748B",
              }),
            ],
            spacing: { before: 240 },
          }),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(document);
  const downloadUrl = URL.createObjectURL(blob);
  const link = window.document.createElement("a");

  try {
    link.href = downloadUrl;
    link.download = sanitizeFileName(fileName);

    window.document.body.appendChild(link);
    link.click();
  } finally {
    link.remove();
    window.setTimeout(() => URL.revokeObjectURL(downloadUrl), 1000);
  }
};