const sanitizeFileName = (fileName) => {
  const cleanedFileName = fileName
    .replace(/[<>:"/\\|?*]/g, "")
    .trim()
    .replace(/\s+/g, "-");

  return cleanedFileName.toLowerCase().endsWith(".txt")
    ? cleanedFileName
    : `${cleanedFileName}.txt`;
};

const stripMarkdown = (content) => {
  return content
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/__(.*?)__/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/_(.*?)_/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/^[-*_]{3,}\s*$/gm, "")
    .replace(/^\s*[-*+]\s+/gm, "• ")
    .trim();
};

export const exportContentAsTxt = (
  title,
  content,
  fileName = "tanio-ai-content.txt"
) => {
  if (!content || !content.trim()) {
    throw new Error("There is no content available to export.");
  }

  const txtContent = `${title}

${stripMarkdown(content)}

Generated by Tanio AI
`;

  const blob = new Blob([txtContent], {
    type: "text/plain;charset=utf-8",
  });

  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = sanitizeFileName(fileName);

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
};