import { jsPDF } from "jspdf";

const cleanMarkdown = (content) => {
  return content
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/__(.*?)__/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/_(.*?)_/g, "$1")
    .replace(/^[-*_]{3,}\s*$/gm, "")
    .replace(/^\s*[-*+]\s+/gm, "• ")
    .replace(/^\s*(\d+)\.\s+/gm, "$1. ")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
};

const sanitizeFileName = (fileName) => {
  const cleanedFileName = fileName
    .replace(/[<>:"/\\|?*]/g, "")
    .trim()
    .replace(/\s+/g, "-");

  return cleanedFileName.toLowerCase().endsWith(".pdf")
    ? cleanedFileName
    : `${cleanedFileName}.pdf`;
};

export const exportContentAsPdf = (
  title,
  content,
  fileName = "tanio-ai-content.pdf"
) => {
  if (!content || !content.trim()) {
    throw new Error("There is no content available to export.");
  }

  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  const leftMargin = 20;
  const rightMargin = 20;
  const topMargin = 20;
  const bottomMargin = 20;
  const usableWidth = pageWidth - leftMargin - rightMargin;

  let yPosition = topMargin;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(18);

  const titleLines = pdf.splitTextToSize(
    title || "Tanio AI Generated Content",
    usableWidth
  );

  pdf.text(titleLines, leftMargin, yPosition);
  yPosition += titleLines.length * 8 + 8;

  pdf.setDrawColor(180);
  pdf.line(leftMargin, yPosition, pageWidth - rightMargin, yPosition);
  yPosition += 10;

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);

  const cleanedContent = cleanMarkdown(content);
  const paragraphs = cleanedContent.split("\n");

  paragraphs.forEach((paragraph) => {
    const trimmedParagraph = paragraph.trim();

    if (!trimmedParagraph) {
      yPosition += 4;
      return;
    }

    const lines = pdf.splitTextToSize(trimmedParagraph, usableWidth);

    lines.forEach((line) => {
      if (yPosition > pageHeight - bottomMargin) {
        pdf.addPage();
        yPosition = topMargin;
      }

      pdf.text(line, leftMargin, yPosition);
      yPosition += 6;
    });

    yPosition += 2;
  });

  const totalPages = pdf.getNumberOfPages();

  for (let pageNumber = 1; pageNumber <= totalPages; pageNumber += 1) {
    pdf.setPage(pageNumber);
    pdf.setFontSize(9);
    pdf.setTextColor(120);

    pdf.text(
      `Generated by Tanio AI • Page ${pageNumber} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      {
        align: "center",
      }
    );
  }

  pdf.save(sanitizeFileName(fileName));
};